Repository TusharAMD/SuperSpeechSaga, pull requests merged in 2024-05, with the labels that each got.

#5 Added the Code of Conduct
  CODE_OF_CONDUCT.md
Labels: GSSoC24

#12 Solved : Enhance README.md file #2
  CONTRIBUTION.md
  README.md
Labels: GSSoC24

#16 created learn.md
  Learn.md
Labels: gssoc, level2

#29 ISSUE-REQUEST-TEMPLATE
  .github/ISSUE_TEMPLATE/bug_request_template.md
Labels: gssoc

#43 Create autocomment-issue.yml
  .github/workflows/autocomment-issue.yml
Labels: gssoc

#49 Update CONTRIBUTION.md
  CONTRIBUTION.md
Labels: gssoc, level1

#64 Update README.md
  README.md
Labels: gssoc, level1
